[font]
size = 15

[font.bold]
family = "Agave Nerd Font"
style = "Bold"

[font.italic]
family = "Agave Nerd Font"
style = "Italic"

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]

[window]
dynamic_title = true
decorations = "full"
dynamic_padding = true
opacity = 1
# startup_mode = "Maximized"

[window.padding]
x = 6
# y = 4

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  {key = "F11", action = 'ToggleFullscreen'},
]

