[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
dynamic_title = true
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"


# [window.padding]
# x = 6
# y = 4

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  {key = "F11", action = 'ToggleFullscreen'},
]

[terminal]

